// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const modal: string;
export const modalContent: string;
export const close: string;
export const inputsContainer: string;
export const submitBtn: string;
