// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const main: string;
export const header: string;
export const date: string;
export const title: string;
