// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const sidebar: string;
export const logo: string;
export const navItemsContainer: string;
export const navItem: string;
