// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const processLibrary: string;
export const processesContainer: string;
export const title: string;
export const processHeader: string;
export const createProcessCta: string;
